name: crypto
favicon: null
layout_spectrum: 0.7488919438328594
typography_spectrum: 0.4493316919542849
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7347873831167817
  lightness: 0.887896733591333
  saturation: 0.6860216073691845
  rhythmicContrast: 0.8891583154909313
purpose: []
